// Copyright © 2023 Meroxa, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package internal

import (
	"regexp"
	"testing"

	"github.com/conduitio/conduit-commons/config"
	"github.com/google/go-cmp/cmp"
	"github.com/matryer/is"
)

func TestGenerateCodeWithRegex(t *testing.T) {
	is := is.New(t)
	got := GenerateCode(map[string]config.Parameter{
		"int.param": {
			Default:     "1",
			Description: "my int param with \"quotes\"",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationExclusion{List: []string{"0", "-1"}},
				config.ValidationGreaterThan{V: -3},
				config.ValidationLessThan{V: 3},
			},
		},
		"bool.param": {
			Default:     "true",
			Description: "my bool param",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{
				config.ValidationRegex{Regex: regexp.MustCompile(".*")},
			},
		},
		"string.param": {
			Description: "simple string param",
			Type:        config.ParameterTypeString,
		},
	}, "s3", "SourceConfig")

	want := `// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package s3

import (
	"regexp"

	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigBoolParam   = "bool.param"
	SourceConfigIntParam    = "int.param"
	SourceConfigStringParam = "string.param"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigBoolParam: {
			Default:     "true",
			Description: "my bool param",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{
				config.ValidationRegex{Regex: regexp.MustCompile(".*")},
			},
		},
		SourceConfigIntParam: {
			Default:     "1",
			Description: "my int param with \"quotes\"",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationExclusion{List: []string{"0", "-1"}},
				config.ValidationGreaterThan{V: -3},
				config.ValidationLessThan{V: 3},
			},
		},
		SourceConfigStringParam: {
			Default:     "",
			Description: "simple string param",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
`
	is.Equal("", cmp.Diff(got, want))
}

func TestGenerateCodeWithoutRegex(t *testing.T) {
	is := is.New(t)
	got := GenerateCode(map[string]config.Parameter{
		"int.param": {
			Default:     "1",
			Description: "my int param",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		"duration.param": {
			Default:     "1s",
			Description: "my duration param",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"1s", "2s", "3s"}},
			},
		},
	}, "file", "Config")

	want := `// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package file

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigDurationParam = "duration.param"
	ConfigIntParam      = "int.param"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigDurationParam: {
			Default:     "1s",
			Description: "my duration param",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"1s", "2s", "3s"}},
			},
		},
		ConfigIntParam: {
			Default:     "1",
			Description: "my int param",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
	}
}
`
	is.Equal("", cmp.Diff(got, want))
}
