// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: config/v1/parameter.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type shows the parameter type.
type Parameter_Type int32

const (
	Parameter_TYPE_UNSPECIFIED Parameter_Type = 0
	// Parameter is a string.
	Parameter_TYPE_STRING Parameter_Type = 1
	// Parameter is an integer.
	Parameter_TYPE_INT Parameter_Type = 2
	// Parameter is a float.
	Parameter_TYPE_FLOAT Parameter_Type = 3
	// Parameter is a boolean.
	Parameter_TYPE_BOOL Parameter_Type = 4
	// Parameter is a file.
	Parameter_TYPE_FILE Parameter_Type = 5
	// Parameter is a duration.
	Parameter_TYPE_DURATION Parameter_Type = 6
)

// Enum value maps for Parameter_Type.
var (
	Parameter_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_STRING",
		2: "TYPE_INT",
		3: "TYPE_FLOAT",
		4: "TYPE_BOOL",
		5: "TYPE_FILE",
		6: "TYPE_DURATION",
	}
	Parameter_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_STRING":      1,
		"TYPE_INT":         2,
		"TYPE_FLOAT":       3,
		"TYPE_BOOL":        4,
		"TYPE_FILE":        5,
		"TYPE_DURATION":    6,
	}
)

func (x Parameter_Type) Enum() *Parameter_Type {
	p := new(Parameter_Type)
	*p = x
	return p
}

func (x Parameter_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Parameter_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_parameter_proto_enumTypes[0].Descriptor()
}

func (Parameter_Type) Type() protoreflect.EnumType {
	return &file_config_v1_parameter_proto_enumTypes[0]
}

func (x Parameter_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Parameter_Type.Descriptor instead.
func (Parameter_Type) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_parameter_proto_rawDescGZIP(), []int{0, 0}
}

type Validation_Type int32

const (
	Validation_TYPE_UNSPECIFIED Validation_Type = 0
	// Parameter must be present.
	Validation_TYPE_REQUIRED Validation_Type = 1
	// Parameter must be greater than {value}.
	Validation_TYPE_GREATER_THAN Validation_Type = 2
	// Parameter must be less than {value}.
	Validation_TYPE_LESS_THAN Validation_Type = 3
	// Parameter must be included in the comma separated list {value}.
	Validation_TYPE_INCLUSION Validation_Type = 4
	// Parameter must not be included in the comma separated list {value}.
	Validation_TYPE_EXCLUSION Validation_Type = 5
	// Parameter must match the regex {value}.
	Validation_TYPE_REGEX Validation_Type = 6
)

// Enum value maps for Validation_Type.
var (
	Validation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_REQUIRED",
		2: "TYPE_GREATER_THAN",
		3: "TYPE_LESS_THAN",
		4: "TYPE_INCLUSION",
		5: "TYPE_EXCLUSION",
		6: "TYPE_REGEX",
	}
	Validation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":  0,
		"TYPE_REQUIRED":     1,
		"TYPE_GREATER_THAN": 2,
		"TYPE_LESS_THAN":    3,
		"TYPE_INCLUSION":    4,
		"TYPE_EXCLUSION":    5,
		"TYPE_REGEX":        6,
	}
)

func (x Validation_Type) Enum() *Validation_Type {
	p := new(Validation_Type)
	*p = x
	return p
}

func (x Validation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Validation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_parameter_proto_enumTypes[1].Descriptor()
}

func (Validation_Type) Type() protoreflect.EnumType {
	return &file_config_v1_parameter_proto_enumTypes[1]
}

func (x Validation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Validation_Type.Descriptor instead.
func (Validation_Type) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_parameter_proto_rawDescGZIP(), []int{1, 0}
}

// Parameter describes a single config parameter.
type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Default is the default value of the parameter. If there is no default
	// value use an empty string.
	Default string `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	// Description explains what the parameter does and how to configure it.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Type defines the parameter data type.
	Type Parameter_Type `protobuf:"varint,3,opt,name=type,proto3,enum=config.v1.Parameter_Type" json:"type,omitempty"`
	// Validations are validations to be made on the parameter.
	Validations []*Validation `protobuf:"bytes,4,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_parameter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_parameter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_config_v1_parameter_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetType() Parameter_Type {
	if x != nil {
		return x.Type
	}
	return Parameter_TYPE_UNSPECIFIED
}

func (x *Parameter) GetValidations() []*Validation {
	if x != nil {
		return x.Validations
	}
	return nil
}

// Validation to be made on the parameter.
type Validation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Validation_Type `protobuf:"varint,1,opt,name=type,proto3,enum=config.v1.Validation_Type" json:"type,omitempty"`
	// The value to be compared with the parameter,
	// or a comma separated list in case of Validation.TYPE_INCLUSION or Validation.TYPE_EXCLUSION.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Validation) Reset() {
	*x = Validation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_parameter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validation) ProtoMessage() {}

func (x *Validation) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_parameter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validation.ProtoReflect.Descriptor instead.
func (*Validation) Descriptor() ([]byte, []int) {
	return file_config_v1_parameter_proto_rawDescGZIP(), []int{1}
}

func (x *Validation) GetType() Validation_Type {
	if x != nil {
		return x.Type
	}
	return Validation_TYPE_UNSPECIFIED
}

func (x *Validation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_config_v1_parameter_proto protoreflect.FileDescriptor

var file_config_v1_parameter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x22, 0xad, 0x02, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x37, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x7c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x4c,
	0x4f, 0x41, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x4f,
	0x4f, 0x4c, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c,
	0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x55, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x22, 0xe7, 0x01, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a,
	0x11, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x48,
	0x41, 0x4e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x45, 0x53,
	0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x58, 0x43, 0x4c, 0x55, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x05,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x45, 0x58, 0x10, 0x06,
	0x42, 0xa3, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x76, 0x31, 0x42, 0x0e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75,
	0x69, 0x74, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_v1_parameter_proto_rawDescOnce sync.Once
	file_config_v1_parameter_proto_rawDescData = file_config_v1_parameter_proto_rawDesc
)

func file_config_v1_parameter_proto_rawDescGZIP() []byte {
	file_config_v1_parameter_proto_rawDescOnce.Do(func() {
		file_config_v1_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_v1_parameter_proto_rawDescData)
	})
	return file_config_v1_parameter_proto_rawDescData
}

var file_config_v1_parameter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_v1_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_v1_parameter_proto_goTypes = []interface{}{
	(Parameter_Type)(0),  // 0: config.v1.Parameter.Type
	(Validation_Type)(0), // 1: config.v1.Validation.Type
	(*Parameter)(nil),    // 2: config.v1.Parameter
	(*Validation)(nil),   // 3: config.v1.Validation
}
var file_config_v1_parameter_proto_depIdxs = []int32{
	0, // 0: config.v1.Parameter.type:type_name -> config.v1.Parameter.Type
	3, // 1: config.v1.Parameter.validations:type_name -> config.v1.Validation
	1, // 2: config.v1.Validation.type:type_name -> config.v1.Validation.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_v1_parameter_proto_init() }
func file_config_v1_parameter_proto_init() {
	if File_config_v1_parameter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_v1_parameter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_parameter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_v1_parameter_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_parameter_proto_goTypes,
		DependencyIndexes: file_config_v1_parameter_proto_depIdxs,
		EnumInfos:         file_config_v1_parameter_proto_enumTypes,
		MessageInfos:      file_config_v1_parameter_proto_msgTypes,
	}.Build()
	File_config_v1_parameter_proto = out.File
	file_config_v1_parameter_proto_rawDesc = nil
	file_config_v1_parameter_proto_goTypes = nil
	file_config_v1_parameter_proto_depIdxs = nil
}
