// Code generated by "stringer -type=ParameterType -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParameterTypeString-1]
	_ = x[ParameterTypeInt-2]
	_ = x[ParameterTypeFloat-3]
	_ = x[ParameterTypeBool-4]
	_ = x[ParameterTypeFile-5]
	_ = x[ParameterTypeDuration-6]
}

const _ParameterType_name = "stringintfloatboolfileduration"

var _ParameterType_index = [...]uint8{0, 6, 9, 14, 18, 22, 30}

func (i ParameterType) String() string {
	i -= 1
	if i < 0 || i >= ParameterType(len(_ParameterType_index)-1) {
		return "ParameterType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ParameterType_name[_ParameterType_index[i]:_ParameterType_index[i+1]]
}
