// Code generated by "stringer -type=ValidationType -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValidationTypeRequired-1]
	_ = x[ValidationTypeGreaterThan-2]
	_ = x[ValidationTypeLessThan-3]
	_ = x[ValidationTypeInclusion-4]
	_ = x[ValidationTypeExclusion-5]
	_ = x[ValidationTypeRegex-6]
}

const _ValidationType_name = "requiredgreater-thanless-thaninclusionexclusionregex"

var _ValidationType_index = [...]uint8{0, 8, 20, 29, 38, 47, 52}

func (i ValidationType) String() string {
	i -= 1
	if i < 0 || i >= ValidationType(len(_ValidationType_index)-1) {
		return "ValidationType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ValidationType_name[_ValidationType_index[i]:_ValidationType_index[i+1]]
}
