// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package tags

import (
	"regexp"

	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigMyName  = "my-name"
	ConfigMyParam = "my-param"
	ConfigParam2  = "param2"
	ConfigParam3  = "param3"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigMyName: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigMyParam: {
			Default:     "3",
			Description: "Param1 i am a parameter comment",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationGreaterThan{V: 0},
				config.ValidationLessThan{V: 100},
			},
		},
		ConfigParam2: {
			Default:     "t",
			Description: "",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"true", "t"}},
				config.ValidationExclusion{List: []string{"false", "f"}},
			},
		},
		ConfigParam3: {
			Default:     "yes",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationRegex{Regex: regexp.MustCompile(".*")},
			},
		},
	}
}
